INSERT INTO `building_enum` (id, name) VALUES
(1, "Capital Hall"),
(2, "District Hall"),
(3, "Cannon"),
(4, "Spear Thrower"),
(5, "Air Defense"),
(6, "Multi Cannon"),
(7, "Bomb Tower"),
(8, "Multi Mortar"),
(9, "Super Wizard Tower"),
(10, "Air Bombs"),
(11, "Rapid Rockets"),
(12, "Crusher"),
(13, "Hidden Mega Tesla"),
(14, "Giant Cannon"),
(15, "Rocket Artillery"),
(16, "Inferno Tower"),
(17, "Blast Bow"),
(18, "Super Giant Post"),
(19, "Raid Cart Post"),
(20, "Super Dragon Post"),
(21, "Walls"),
(22, "Mine"),
(23, "Mega Mine"),
(24, "Log Trap"),
(25, "Zap Trap"),
(26, "Army Camp"),
(27, "Spell Storage"),
(28, "Super Barbarian Barracks"),
(29, "Sneaky Archer Barracks"),
(30, "Super Giant Barracks"),
(31, "Battle Ram Barracks"),
(32, "Minion Barracks"),
(33, "Super Wizard Barracks"),
(34, "Rocket Balloon Barracks"),
(35, "Skeleton Barrel Barracks"),
(36, "Flying Fortress Barracks"),
(37, "Raid Cart Barracks"),
(38, "Super P.E.K.K.A Barracks"),
(39, "Hog Raider Barracks"),
(40, "Super Dragon Barracks"),
(41, "Mountain Golem Quarry"),
(42, "Heal Spell Factory"),
(43, "Jump Spell Factory"),
(44, "Lightning Spell Factory"),
(45, "Frost Spell Factory"),
(46, "Rage Spell Factory"),
(47, "Mini-Minion Hive"),
(48, "Reflector");



INSERT INTO `district_enum` (id, name) VALUES
(1, "Clan Capital"),
(2, "Barbarian Camp"),
(3, "Wizard Valley"),
(4, "Balloon Lagoon"),
(5, "Builder's Workshop"),
(6, "Dragon Cliffs"),
(7, "Golem Quarry"),
(8, "Skeleton Park");


